version: "3.8"
services:
  saladejuntas-front:
    container_name: saladejuntas-front
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    restart: always
    stdin_open: true
    volumes:
      - './:/home/app'